import fs from 'fs-extra';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import dotenv from 'dotenv';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);
const rootDir = path.resolve(__dirname, '..');
const srcDir = path.join(rootDir, 'src');
const distDir = path.join(rootDir, 'dist');
const envPath = path.join(rootDir, '.env');

const REQUIRED_ENV_KEYS = ['AI_MODEL_API_KEY', 'AI_MODEL'];

function assertEnv(envConfig) {
  const missingKeys = REQUIRED_ENV_KEYS.filter(
    (key) => !envConfig[key] || envConfig[key].trim().length === 0,
  );

  if (missingKeys.length > 0) {
    throw new Error(
      `Missing required keys in .env: ${missingKeys.join(
        ', ',
      )}\nCopy .env.example to .env and fill in the values.`,
    );
  }
}

async function loadEnv() {
  if (!(await fs.pathExists(envPath))) {
    throw new Error('No .env found. Copy .env.example and provide your API values before building.');
  }

  const parsed = dotenv.config({ path: envPath });
  if (parsed.error || !parsed.parsed) {
    throw parsed.error ?? new Error('Unable to parse .env file.');
  }

  assertEnv(parsed.parsed);
  return parsed.parsed;
}

async function copySource() {
  await fs.ensureDir(distDir);
  await fs.copy(srcDir, distDir);
}

async function writeConfig(envConfig) {
  const configPath = path.join(distDir, 'config.js');
  const jsonPayload = JSON.stringify(
    {
      AI_MODEL_API_KEY: envConfig.AI_MODEL_API_KEY,
      AI_MODEL: envConfig.AI_MODEL,
    },
    null,
    2,
  );

  const fileContents = `// Auto-generated by scripts/build.js. Do not edit manually.\nexport const EXT_CONFIG = Object.freeze(${jsonPayload});\n`;
  await fs.writeFile(configPath, fileContents, 'utf8');
}

async function main() {
  console.info('[build] Cleaning dist directory');
  await fs.remove(distDir);

  console.info('[build] Copying extension source files');
  await copySource();

  console.info('[build] Loading environment configuration');
  const envConfig = await loadEnv();

  console.info('[build] Writing runtime config');
  await writeConfig(envConfig);

  console.info('[build] Done');
}

main().catch((error) => {
  console.error('[build] Failed:', error?.message ?? error);
  process.exitCode = 1;
});
